[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:victoria-metrics]
command=/usr/local/bin/victoria-metrics
    -storageDataPath=/var/lib/victoriametrics
    -httpListenAddr=:8428
    -retentionPeriod=12
    -enableTCP6
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:victoria-logs]
command=/usr/local/bin/victoria-logs
    -storageDataPath=/var/lib/victorialogs
    -httpListenAddr=:9428
    -enableTCP6
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:tempo]
command=/usr/local/bin/tempo -config.file=/etc/tempo-config.yaml
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:otelcol]
command=/usr/local/bin/otelcol --config=/etc/otel-collector-config.yaml
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=20
